from fastapi import FastAPI
from vibeflow import vibe

app = FastAPI()

@app.get("/generate_text")
@vibe
async def generate_text(topic: str) -> dict:
    """Generate a short, two-sentence paragraph about the given topic."""
    ... # The implementation will be generated by vibe

@app.get("/")
async def read_root():
    return {"message": "Welcome to the Vibe-powered FastAPI app! Visit /docs for API details."}
